### ISSUE TITLE
ScriptManager.RegisterClientScriptBlock doesn't output javascript

### ISSUE THREAD

**Issue by eternalbard** [mono/linux-packaging-xsp#1]
Hi, I don't know if this git is the same used on Xamarin Studio, so sorry if I'm writing the wrong place.

But I'm using XSP that came with Xamarin Studio to run our actual project that runs on IIS to be more practical to develop all things on MacOS.

But ScriptManager.RegisterClientScriptBlock is not outputting any script so no JavaScript/JQuery/JQueryMobile is being injected. Any tip?

Thanks.

**Comment by akoeplinger** [comment]
This repository is used for the Linux packaging files of xsp, I'd suggest you file this bug on https://bugzilla.xamarin.com if the issue still exists. Thanks!
